In [1]:

import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
mp_key = "YGuF6wLUiS0cPBcPVPZQwERRrYM11mh7"
mp_id = "mp-22003"

In [4]:
with MPRester(mp_key) as m:
    structure = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(structure).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Structure symmetry

In [5]:
analyzer = SpacegroupAnalyzer(structure)

lattice_vectors = structure.lattice.matrix
print("Vecteurs de base du réseau direct:")
print(lattice_vectors)

reciprocal_lattice_vectors = structure.lattice.reciprocal_lattice.matrix
print("Vecteurs de base du réseau réciproque:")
print(reciprocal_lattice_vectors)

lattice_type = analyzer.get_lattice_type()
print("Type de maille:", lattice_type)

crystal_system = analyzer.get_crystal_system()
print("Système cristallin:", crystal_system)

point_group = analyzer.get_point_group_symbol()
print("Groupe ponctuel:", point_group)

Vecteurs de base du réseau direct:
[[3.41309104 0.01722484 4.30086684]
 [1.51130613 3.0603007  4.30086684]
 [0.02756099 0.01722484 5.49052708]]
Vecteurs de base du réseau réciproque:
[[ 1.85362361 -0.90631717 -0.00646141]
 [-0.0022706   2.06332915 -0.00646166]
 [-1.450211   -0.90631635  1.15449129]]
Type de maille: rhombohedral
Système cristallin: trigonal
Groupe ponctuel: -3m
