In [9]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [10]:
mp_key = "YGuF6wLUiS0cPBcPVPZQwERRrYM11mh7"
mp_id = "mp-22003"

In [26]:
with MPRester(mp_key) as m:
    structure = m.get_structure_by_material_id(mp_id)
    
analyser = SpacegroupAnalyzer(structure)
symm_ops = analyser.get_symmetry_operations()
conv_struc = analyser.get_conventional_standard_structure()
print(len(symm_ops))

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

24


In [109]:
selected_ops = [symm_ops[6], symm_ops[8], symm_ops[2]] # choix des opérations
sites = conv_struc.sites
selected_sites = [sites[4],sites[1],sites[2]] # choix des atomes (N,Na,Na)
print(len(sites))
print(sites)

12
[PeriodicSite: Na (0.0, 0.0, 0.0) [0.0, 0.0, 0.0], PeriodicSite: Na (1.794, -1.036, 5.085) [0.6667, 0.3333, 0.3333], PeriodicSite: Na (1.794, 1.036, 10.17) [0.3333, 0.6667, 0.6667], PeriodicSite: N (1.794, -1.036, 13.89) [0.6667, 0.3333, 0.9106], PeriodicSite: N (1.794, -1.036, 12.71) [0.6667, 0.3333, 0.8333], PeriodicSite: N (1.794, -1.036, 11.53) [0.6667, 0.3333, 0.7561], PeriodicSite: N (1.794, 1.036, 3.721) [0.3333, 0.6667, 0.2439], PeriodicSite: N (1.794, 1.036, 2.542) [0.3333, 0.6667, 0.1667], PeriodicSite: N (1.794, 1.036, 1.364) [0.3333, 0.6667, 0.08939], PeriodicSite: N (0.0, 0.0, 8.806) [0.0, 0.0, 0.5773], PeriodicSite: N (3.588, 4.441e-16, 7.627) [1.0, 1.0, 0.5], PeriodicSite: N (0.0, 0.0, 6.448) [0.0, 0.0, 0.4227]]


In [111]:
N1 = selected_sites[0]
operation1 = selected_ops[0]
print(operation1) # rotation 120° -> det A = 1 -> conserve la chiralité
print(N1.frac_coords)
print(operation1.operate(N1.frac_coords))

view1 = quick_view(conv_struc,supercell=[1,1,1])
display(view1)
view1.script('draw symop 7 {atomno = 5}; select atomno=5; label on; color red')

Rot:
[[ 0.  0. -1.]
 [-1.  0.  0.]
 [ 0. -1.  0.]]
tau
[0. 0. 0.]
[0.66666667 0.33333333 0.83333333]
[-0.83333333 -0.66666667 -0.33333333]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [91]:
Na1 = selected_sites[1]
operation2 = selected_ops[1]
print(operation2) # roto-réflexion (réflexion + rotation de 120°) -> det A = -1 -> inverse la chiralité
print(Na1.frac_coords)
print(operation2.operate(Na1.frac_coords))

view2 = quick_view(conv_struc,supercell=[1,1,1])
display(view2)
view2.script('draw symop 9 {atomno = 2}; select atomno=2; label on; color red')

Rot:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
[0.66666667 0.33333333 0.33333333]
[0.33333333 0.33333333 0.66666667]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [100]:
Na2 = selected_sites[2]
operation3 = selected_ops[2]
print(operation3) # inversion -> det A = -1 -> inverse la chiralité
print(Na2.frac_coords)
print(operation3.operate(Na2.frac_coords))

view3 = quick_view(conv_struc,supercell=[1,1,1])
display(view3)
view3.script('draw symop 3 {atomno = 3}; select atomno=3; label on; color red')

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
[0.33333333 0.66666667 0.66666667]
[-0.33333333 -0.66666667 -0.66666667]


JsmolView(layout=Layout(align_self='stretch', height='400px'))